name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e_playwright:
    name: Frontend E2E (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Always install Node first (no cache)
      - name: Setup Node.js (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) If using pnpm, install pnpm tool here
      - name: Setup pnpm
        if: ${{ hashFiles('frontend/pnpm-lock.yaml') != '' }}
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3) If using yarn, enable via corepack (optional but robust)
      - name: Setup Yarn (via corepack)
        if: ${{ hashFiles('frontend/yarn.lock') != '' }}
        run: |
          corepack enable
          corepack prepare yarn@1.22.19 --activate

      # 4) Enable npm cache only when package-lock.json exists
      - name: Enable npm cache (only when package-lock.json exists)
        if: ${{ hashFiles('frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # Install frontend deps using the matching package manager
      - name: Install frontend deps
        working-directory: ./frontend
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile;
          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile;
          else npm ci; fi

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm run build;
          elif [ -f yarn.lock ]; then yarn build;
          else npm run build; fi

      # Start server + robust readiness: try /assessment, fallback to /
      - name: Start frontend server (bg) with robust readiness
        env:
          READINESS_PATH: "/"
        run: |
          set -euo pipefail
          LOG=frontend_server.log

          # Start server in background and capture logs
          if [ -f frontend/pnpm-lock.yaml ]; then
            nohup bash -c "cd frontend && pnpm start" >"$LOG" 2>&1 &
          elif [ -f frontend/yarn.lock ]; then
            nohup bash -c "cd frontend && yarn start" >"$LOG" 2>&1 &
          else
            nohup bash -c "cd frontend && npm run start" >"$LOG" 2>&1 &
          fi

          # Probe readiness via HTTP status (2xx/3xx = ready)
          for path in /assessment ${READINESS_PATH}; do
            echo "Probing $path ..."
            for i in {1..120}; do
              code="$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3000${path}" || echo 000)"
              if [ "$code" -ge 200 ] && [ "$code" -lt 400 ]; then
                echo "Frontend is up on $path (HTTP $code)."
                exit 0
              fi
              echo "[$i] Waiting... HTTP $code"
              sleep 2
            done
          done

          echo "❌ Timeout. Last 200 lines of server log:"
          tail -n 200 "$LOG" || true
          exit 1

      # Install Playwright browsers + a11y helper
      - name: Install Playwright + a11y deps
        run: |
          ( [ -f test/package.json ] && ( npm -C test ci || npm -C test install ) ) || npm -C test install --no-save @axe-core/playwright
          npx playwright install --with-deps

      # Run E2E tests (trace/screenshot/video enabled, retries=1)
      - name: Run Playwright tests (trace/screenshot/video, retries=1)
        env:
          CI: true
        run: npx playwright test -c test/playwright.config.ts

      # Upload reports and traces
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test/playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results
          if-no-files-found: ignore

  backend_pytest:
    name: Backend Tests (pytest + coverage)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # Install all runtime + test deps from files (root-cause fix for httpx etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Run pytest with coverage gate (>=80%)
      - name: Run pytest with coverage gate (>=80%)
        run: pytest

      # Upload coverage.xml for review
      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore

  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1) Always install Node first (no cache)
      - name: Setup Node.js (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2) If using pnpm, install pnpm
      - name: Setup pnpm
        if: ${{ hashFiles('frontend/pnpm-lock.yaml') != '' }}
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 3) If using yarn, enable via corepack
      - name: Setup Yarn (via corepack)
        if: ${{ hashFiles('frontend/yarn.lock') != '' }}
        run: |
          corepack enable
          corepack prepare yarn@1.22.19 --activate

      # 4) Enable npm cache only when package-lock.json exists
      - name: Enable npm cache (only when package-lock.json exists)
        if: ${{ hashFiles('frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend deps
        working-directory: ./frontend
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile;
          elif [ -f yarn.lock ]; then yarn install --frozen-lockfile;
          else npm ci; fi

      - name: Build frontend
        working-directory: ./frontend
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm run build;
          elif [ -f yarn.lock ]; then yarn build;
          else npm run build; fi

      - name: Start frontend server (bg) with robust readiness
        env:
          READINESS_PATH: "/"
        run: |
          set -euo pipefail
          LOG=frontend_server.log
          if [ -f frontend/pnpm-lock.yaml ]; then
            nohup bash -c "cd frontend && pnpm start" >"$LOG" 2>&1 &
          elif [ -f frontend/yarn.lock ]; then
            nohup bash -c "cd frontend && yarn start" >"$LOG" 2>&1 &
          else
            nohup bash -c "cd frontend && npm run start" >"$LOG" 2>&1 &
          fi

          for path in ${READINESS_PATH}; do
            for i in {1..120}; do
              code="$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:3000${path}" || echo 000)"
              if [ "$code" -ge 200 ] && [ "$code" -lt 400 ]; then
                echo "Frontend is up on $path (HTTP $code)."
                exit 0
              fi
              echo "[$i] Waiting... HTTP $code"
              sleep 2
            done
          done

          echo "❌ Timeout. Last 200 lines of server log:"
          tail -n 200 "$LOG" || true
          exit 1

      - name: Run Lighthouse CI (using test/lighthouserc.json)
        run: |
          npm -C test install --no-save @lhci/cli@0.13.x
          npx --yes lhci autorun --config=./test/lighthouserc.json

      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: ./.lighthouseci
          if-no-files-found: ignore
